### PR TITLE
refactor(*): adjust profileExchange event names & subscriptions

### PR DESCRIPTION
**Pull request by ramfox**
- issues when all testing is exec:go/local:exec-> connections happen btw the different local nodes
- need to add back `ShareInfo` & `connectAllNodes` so that each node connects & initiates the exchange
- I think waiting for 'sendAttempts' is the best move still, need to remove the wait group I added in a previous attempt to sync.

### CODE REVIEW

**Comment by ramfox** [comment]
set back on test-plans front, have done a few iterations, including using code straight pulled from an ipfs test plan and I am unable to get one peer to dial to another successfully. 
```
Error while dialing peer [/ip4/127.0.0.1/tcp/44197 /ip6/::1/tcp/43939 /ip4/127.0.0.1/udp/43812/quic /ip6/::1/udp/38458/quic]: failed to dial QmUL81TkJCrMisU8Mdy2c94arfMC7auX3RLpuckb9u8vDr: all dials failed
  * [/ip6/::1/tcp/43939] dial tcp6 [::1]:43939: connect: cannot assign requested address
  * [/ip6/::1/udp/38458/quic] write udp6 [::]:38429->[::1]:38458: sendto: cannot assign requested address
  * [/ip4/127.0.0.1/tcp/44197] dial tcp4 127.0.0.1:44197: connect: connection refused
  * [/ip4/127.0.0.1/udp/43812/quic] NO_ERROR: Handshake did not complete in time
```

this is with us just calling libp2p's `host.Connect(ctx, AddrInfo)`
wondering if there is something wrong with my set up now, since the error is also happening on test plan tests that were previously able to connect. I recently updated docker and I wonder if that is somehow related

**Comment by ramfox** [comment]
Okay, so:
- updated testgrounds to latest release
- pruned docker volumes
- restarted docker

nodes are able to connect in exec again, however all docker tests now are having trouble

I believe the issue is the way we are creating temp paths and directories when we create an actor. Going to look into this deeper.

**Comment by ramfox** [comment]
```
$ testground run single -p qri -t test -b docker:go -r local:docker -i 2
Aug  7 01:31:29.918664	INFO	created a synthetic composition file for this job; all instances will run under singleton group "single"
Aug  7 01:31:29.918729	INFO	using home directory: /Users/ramfox/Work/testground
Aug  7 01:31:29.919333	INFO	.env.toml loaded from: /Users/ramfox/Work/testground/.env.toml
Aug  7 01:31:29.919346	INFO	testground client initialized	{"addr": "http://localhost:8080"}
Aug  7 01:31:29.919909	INFO	using home directory: /Users/ramfox/Work/testground
Aug  7 01:31:29.920025	INFO	.env.toml loaded from: /Users/ramfox/Work/testground/.env.toml
Aug  7 01:31:29.920043	INFO	testground client initialized	{"addr": "http://localhost:8080"}
Aug  7 01:31:29.920331	INFO	test plan source at: /Users/ramfox/Work/testground/plans/qri

>>> Server output:

Aug  7 01:31:30.641086	INFO	performing build for groups	{"req_id": "dfdbaeeb", "plan": "qri", "groups": ["single"], "builder": "docker:go"}
Aug  7 01:31:30.648965	INFO	found existing volume	{"req_id": "dfdbaeeb", "volume_name": "testground-goproxy-vol"}
Aug  7 01:31:30.658940	INFO	container is already running	{"req_id": "dfdbaeeb", "container_name": "testground-goproxy"}
Step 1/22 : ARG BUILD_BASE_IMAGE
Step 2/22 : ARG RUNTIME_IMAGE=busybox:1.31.1-glibc
Step 3/22 : FROM ${BUILD_BASE_IMAGE} AS builder
 ---> 00d970a31ef2
Step 4/22 : ENV PLAN_DIR /plan
 ---> Using cache
 ---> cc6be1514839
Step 5/22 : ENV SDK_DIR /sdk
 ---> Using cache
 ---> 0a1fe5bfcb18
Step 6/22 : RUN rm -rf ${PLAN_DIR} ${SDK_DIR} /testground_dep_list
 ---> Using cache
 ---> 52df24295b2f
Step 7/22 : ARG TESTPLAN_EXEC_PKG="."
 ---> Using cache
 ---> 2fced8aedf78
Step 8/22 : ARG GO_PROXY=direct
 ---> Using cache
 ---> 63caaca5e8f3
Step 9/22 : ARG BUILD_TAGS
 ---> Using cache
 ---> 824b7d8c2bfc
Step 10/22 : ENV TESTPLAN_EXEC_PKG ${TESTPLAN_EXEC_PKG}
 ---> Using cache
 ---> bce249564831
Step 11/22 : ENV GOCACHE /go/cache
 ---> Using cache
 ---> 9f92374e0485
Step 12/22 : COPY /plan/go.mod ${PLAN_DIR}/go.mod
 ---> Using cache
 ---> d90122393a98
Step 13/22 : RUN echo "Using go proxy: ${GO_PROXY}"     && cd ${PLAN_DIR}     && go env -w GOPROXY="${GO_PROXY}"     && go mod download
 ---> Using cache
 ---> c0c2094af4e6
Step 14/22 : COPY . /
 ---> cecd1bc24877
Step 15/22 : RUN cd ${PLAN_DIR}     && go env -w GOPROXY="${GO_PROXY}"     && GOOS=linux GOARCH=amd64 go build -o ${PLAN_DIR}/testplan.bin ${BUILD_TAGS} ${TESTPLAN_EXEC_PKG}
 ---> Running in 6a61c950c686
 ---> 5d6aa5bc9a72
Step 16/22 : RUN cd ${PLAN_DIR}   && go list -m all > /testground_dep_list
 ---> Running in a924affbc484
 ---> fa5853be8764
 ---> fa5853be8764
Step 17/22 : FROM ${RUNTIME_IMAGE} AS runtime
 ---> 7a2331af2292
Step 18/22 : ENV PLAN_DIR /plan
 ---> Using cache
 ---> 84fda0e4b38a
Step 19/22 : COPY --from=builder /testground_dep_list /
 ---> Using cache
 ---> ebf0c08749c2
Step 20/22 : COPY --from=builder ${PLAN_DIR}/testplan.bin /testplan
 ---> 41b69196de3f
Step 21/22 : EXPOSE 6060
 ---> Running in d757f7795cdf
 ---> 78abfceccfc7
Step 22/22 : ENTRYPOINT [ "/testplan"]
 ---> Running in 097bc99023cc
 ---> cba6c75debd2
 ---> cba6c75debd2
Successfully built cba6c75debd2
Successfully tagged f79736eb09fd:latest
Aug  7 01:33:06.243785	INFO	build completed	{"req_id": "dfdbaeeb", "default_tag": "f79736eb09fd:latest", "took": "1m35s"}
Aug  7 01:33:06.520694	INFO	got docker image id	{"req_id": "dfdbaeeb", "image_id": "cba6c75debd2"}
Aug  7 01:33:06.658481	INFO	tagging image	{"req_id": "dfdbaeeb", "image_id": "cba6c75debd2", "tag": "tg-plan-qri:cba6c75debd2"}
Aug  7 01:33:06.665625	INFO	build succeeded	{"req_id": "dfdbaeeb", "plan": "qri", "groups": ["single"], "builder": "docker:go", "artifact": "cba6c75debd2"}

>>> Result:

Aug  7 01:33:06.668190	INFO	generated build artifact	{"group": "single", "artifact": "cba6c75debd2"}

>>> Server output:

Aug  7 01:33:06.669368	INFO	performing healthcheck on runner	{"req_id": "b3340954"}
Aug  7 01:33:06.727951	INFO	healthcheck: ok	{"req_id": "b3340954"}
Aug  7 01:33:21.847268	INFO	creating container	{"req_id": "b3340954", "runner": "local:docker", "run_id": "f606a6aa9127", "name": "tg-qri-test-f606a6aa9127-single-0"}
Aug  7 01:33:21.993183	INFO	creating container	{"req_id": "b3340954", "runner": "local:docker", "run_id": "f606a6aa9127", "name": "tg-qri-test-f606a6aa9127-single-1"}
Aug  7 01:33:22.142236	INFO	starting containers	{"req_id": "b3340954", "runner": "local:docker", "run_id": "f606a6aa9127", "count": 2}
Aug  7 01:33:22.142411	INFO	starting container	{"req_id": "b3340954", "runner": "local:docker", "run_id": "f606a6aa9127", "id": "ecbb61bc4c7d6e65af328f40502684c9b94281b763c69c654eefc80158edd1ec", "group": "single", "group_index": 0}
Aug  7 01:33:22.142532	INFO	starting container	{"req_id": "b3340954", "runner": "local:docker", "run_id": "f606a6aa9127", "id": "76d23ab2abea5f7d87e201761e3833e5b4f4976e78b0a7a029801aec99594298", "group": "single", "group_index": 1}
Aug  7 01:33:22.773497	INFO	0.6311s      ERROR << single[000] (ecbb61) >> /testplan: error while loading shared libraries: libdl.so.2: cannot open shared object file: No such file or directory	{"req_id": "b3340954"}
Aug  7 01:33:22.789809	INFO	0.6474s      OTHER << sidecar      >> Aug  7 01:33:22.787305	INFO	resolved route to host	{"host": "testground-redis", "ip": "192.18.0.2"}	{"req_id": "b3340954"}
Aug  7 01:33:22.798838	INFO	0.6565s      OTHER << sidecar      >> Aug  7 01:33:22.796442	INFO	resolved route to host	{"host": "testground-influxdb", "ip": "192.18.0.5"}	{"req_id": "b3340954"}
Aug  7 01:33:22.799329	INFO	0.6543s    MESSAGE << sidecar      >> InfluxDB unavailable; no metrics will be dispatched: no InfluxDB URL in $INFLUXDB_URL env var	{"req_id": "b3340954"}
Aug  7 01:33:22.803402	INFO	0.6610s      OTHER << sidecar      >> Aug  7 01:33:22.799997	ERROR	sidecar worker failed: failed to initialise the container: failed to lookup the net namespace: no such file or directory	{"host": "unix:///var/run/docker.sock", "container": "ecbb61bc4c7d6e65af328f40502684c9b94281b763c69c654eefc80158edd1ec"}	{"req_id": "b3340954"}
Aug  7 01:33:22.856366	INFO	started containers	{"req_id": "b3340954", "runner": "local:docker", "run_id": "f606a6aa9127", "count": 2}
Aug  7 01:33:22.862144	INFO	0.7198s      ERROR << single[001] (76d23a) >> /testplan: error while loading shared libraries: libdl.so.2: cannot open shared object file: No such file or directory	{"req_id": "b3340954"}
Aug  7 01:33:22.883584	INFO	0.7282s    MESSAGE << sidecar      >> InfluxDB unavailable; no metrics will be dispatched: no InfluxDB URL in $INFLUXDB_URL env var	{"req_id": "b3340954"}
Aug  7 01:33:22.885787	INFO	0.7434s INCOMPLETE << single[000] (ecbb61) >> 	{"req_id": "b3340954"}
Aug  7 01:33:22.888958	INFO	0.7466s      OTHER << sidecar      >> Aug  7 01:33:22.887856	ERROR	sidecar worker failed: failed to initialise the container: failed to lookup the net namespace: no such file or directory	{"host": "unix:///var/run/docker.sock", "container": "76d23ab2abea5f7d87e201761e3833e5b4f4976e78b0a7a029801aec99594298"}	{"req_id": "b3340954"}
Aug  7 01:33:22.956241	INFO	0.8138s INCOMPLETE << single[001] (76d23a) >> 	{"req_id": "b3340954"}
Aug  7 01:33:22.956369	INFO	deleting containers	{"req_id": "b3340954", "runner": "local:docker", "run_id": "f606a6aa9127", "ids": ["ecbb61bc4c7d6e65af328f40502684c9b94281b763c69c654eefc80158edd1ec", "76d23ab2abea5f7d87e201761e3833e5b4f4976e78b0a7a029801aec99594298"]}
Aug  7 01:33:22.956441	INFO	deleting container	{"req_id": "b3340954", "runner": "local:docker", "run_id": "f606a6aa9127", "id": "76d23ab2abea5f7d87e201761e3833e5b4f4976e78b0a7a029801aec99594298"}
Aug  7 01:33:22.956680	INFO	deleting container	{"req_id": "b3340954", "runner": "local:docker", "run_id": "f606a6aa9127", "id": "ecbb61bc4c7d6e65af328f40502684c9b94281b763c69c654eefc80158edd1ec"}
Aug  7 01:33:22.956783	INFO	0.8144s INCOMPLETE << sidecar      >> 	{"req_id": "b3340954"}
Aug  7 01:33:23.206097	WARN	run finished in error	{"req_id": "b3340954", "run_id": "f606a6aa9127", "plan": "qri", "case": "test", "runner": "local:docker", "instances": 2, "error": "2 nodes failed"}
Aug  7 01:33:23.206184	WARN	engine run error: 2 nodes failed	{"req_id": "b3340954"}
```

So this error comes in anytime we reference something from qri! all other imports are fine (checked with qfs & dataset). 

I've been smashing my face against this all day trying isolate the problem. Now that I've got a better idea, I'll pick it up tomorrow.

You can re-pro:

main.go:
```
package main

import {
	"github.com/qri-io/qri/lib"
	sdk_run "github.com/testground/sdk-go/run"
	"github.com/testground/sdk-go/runtime"
)

func main() {
	sdk_run.Invoke(run)
}

func run(runenv *runtime.RunEnv) error {
	runenv.RecordMessage("instance: %s", lib.Instance{})
	runenv.RecordMessage("hello world!")
	return nil
}
```

go.mod
```
module github.com/qri-io/test-plans

go 1.14

require (
	github.com/libp2p/go-libp2p-core v0.5.7
	github.com/libp2p/go-libp2p-peer v0.2.0
	github.com/qri-io/dataset v0.2.0
	github.com/qri-io/ioes v0.1.1
	github.com/qri-io/qfs v0.5.1-0.20200722134009-7b5ac5539ce7
	github.com/qri-io/qri v0.9.10
	github.com/testground/sdk-go v0.2.4
	golang.org/x/sync v0.0.0-20200317015054-43a5402ce75a
)
```

manifest.toml
```
name = "qri"
[defaults]
builder = "exec:go"
runner = "local:exec"

[builders."docker:go"]
enabled = true
go_version = "1.14"
module_path = "github.com/qri-io/test-plans"
exec_pkg = "."

[builders."exec:go"]
enabled = true
module_path = "github.com/qri-io/test-plans"

[runners."local:docker"]
enabled = true

[runners."local:exec"]
enabled = true

[runners."cluster:swarm"]
enabled = true

[[testcases]]
name = "push"
instances = { min = 2, max = 200, default = 2 }
  [testcases.params]
  timeout_secs = { type = "int", desc = "test timeout", unit = "seconds", default = 300 }
  latency      = { type = "int", desc = "latency between peers", unit = "ms", default = 100 }
  datasetSize     = { type = "int", desc = "size of the dataset to be pushed", unit = "bytes", default = 1000 }
  pushersPerReceiver     = { type = "int", desc = "number of pusher instances we want to have for each receiver instance. Will error if this number is more then the number of instances in the test case", default = 1 }

[[testcases]]
name = "pull"
instances = { min = 2, max = 200, default = 2 }
  [testcases.params]
  timeout_secs = { type = "int", desc = "test timeout", unit = "seconds", default = 300 }
  latency      = { type = "int", desc = "latency between peers", unit = "ms", default = 100 }
  datasetSize     = { type = "int", desc = "size of the dataset to be pushed", unit = "bytes", default = 1000 }
  pullersPerRemote     = { type = "int", desc = "number of pusher instances we want to have for each receiver instance. Will error if this number is more then the number of instances in the test case", default = 1 }
```

**Comment by ramfox** [comment]
Okay so looks like the problem is that the runtime image that testground uses in it docker image is `busybox:1.31.1-glibc` which does not come with `libdl.so.2`

Going to look to see if there is a version of a runtime busybox docker image that has this library. (https://hub.docker.com/_/busybox)
If that doesn't work, going to use the `manifest.toml` file to add that library directly (`apt-get install -y libdl.so.2`)
If that doesn't work, going to change the runtime images from busybox to debian.

https://stackoverflow.com/questions/29292788/error-running-file-in-container-error-when-loading-shared-libraries-docker#:~:text=2%20Answers&text=The%20error%20tells%20you%20exactly,on%20various%20libraries%20(including%20libkrb5.&text=You%20have%20two%20choices%3B%20you,that%20it%20is%20statically%20linked.

https://github.com/prometheus/busybox/issues/15

**Comment by ramfox** [comment]
re the previous issue: https://github.com/testground/testground/issues/1062

**Comment by ramfox** [comment]
after commit bdfc2cf, test case `pull` shows we can do full p2p pull (ref resolution + logsync + dsync)

**Review by b5 — APPROVED** [review]
LGTM!

**Pull request merged**
